project:
  type: website
  output-dir: _blog
  render:
    - "**/*.qmd"
    - "!MyBlog/"
    - "!param_reports/"
    - "!shiny/"

execute:
  freeze: auto      # only re-execute R code in files that changed
  warning: false

lang: en

brand:
  light: _brand.yml
  dark: _brand-dark.yml

website:
  title: "R4DEV"
  description: "Data workshop on reproducible analysis and visualisation using R, created by Nelson Amaya D."
  favicon: logo/r4dev_dalle_1.png
  site-url: https://r4dev.netlify.app/

  google-analytics:
    tracking-id: "G-CE27LT98M2"
  cookie-consent: true

  twitter-card:
    image: logo/r4dev_dalle_1.png
    title: "R4DEV"
    description: "Data workshop created by Nelson Amaya D."
    card-style: summary
    creator: "@nelsonamayad"

  open-graph:
    image: logo/r4dev_dalle_1.png
    title: "R4DEV"
    description: "Data workshop created by Nelson Amaya D."

  search:
    location: navbar
    type: overlay

  page-navigation: true
  back-to-top-navigation: true

  navbar:
    logo: logo/r4dev_dalle_1.png
    title: false
    background: primary
    foreground: white
    style: floating

    left:
      - text: "Home"
        icon: "house-door"
        href: index.qmd
      - text: "Start here"
        icon: "signpost-2"
        href: start.qmd
      - text: "Learn"
        icon: "mortarboard"
        menu:
          - text: "Build with R"
            icon: "code-slash"
            href: learn/build-with-r.qmd
          - text: "Work with AI"
            icon: "robot"
            href: learn/ai.qmd
          - text: "Think with data"
            icon: "dice-5"
            href: learn/thinking.qmd
      - text: "Practice"
        icon: "trophy"
        href: sessions_tools/01-practice/01-practice.qmd
      - text: "Resources"
        icon: "eye-fill"
        href: sessions_tools/02-resources/02-resources.qmd

    right:
      - text: "About R4DEV"
        icon: "question-circle-fill"
        href: about.qmd

  page-footer:
    left: "📉 R4DEV 📈"

    center: |
      <span class="faux-block">Licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>

    right: |
      <span class="faux-block">Created with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>

    background: primary

format:
  html:
    theme:
      light: [journal, brand]
      dark: [journal, brand]
    respect-user-color-scheme: true
    toc: true
    toc-location: left
    code-fold: show
    code-summary: "Click me!"
    code-tools:
      toggle: true
      source: false
    code-link: true
    code-copy: true
    code-annotations: hover
    highlight-style: arrow
    footnotes-hover: true
    link-external-newwindow: true
    smooth-scroll: true
    lightbox: true
    css: style.css

comments:
  hypothesis: true
